### ISSUE TITLE
Criar prototipo

### ISSUE THREAD

**Issue by motagabriel** [motagabriel/projeto_integrador_2022#1]
Criar telas

**Comment by renathaiglesias** [comment]
https://www.figma.com/proto/2eJt2Q6w1Skf06zbGMr35H/Pet_Adoption_App%5B1%5D?node-id=1%3A2&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A485

**Comment by renathaiglesias** [comment]
https://www.figma.com/proto/2eJt2Q6w1Skf06zbGMr35H/Pet_Adoption_App%5B1%5D?node-id=1%3A485&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A485
